
USE ${DB_NAME};

CREATE TABLE IF NOT EXISTS interest_contact (
  id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
  contact_email VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts (
  id INT AUTO_INCREMENT PRIMARY KEY UNIQUE,
  email VARCHAR(100) NOT NULL
)